<?php
/**
 * Copyright © Swarming Technology, LLC. All rights reserved.
 */

/**
 * @var \Swarming\StoreCredit\Block\Adminhtml\Customer\CreditsTab\Adjustment $block
 */
?>

<div class="entry-edit form-inline" style="float:right; width: 54%;">
    <?php echo $block->getFormHtml();?>
</div>
<?php echo $block->getChildHtml('form_after');?>
<script>
    require([
        'jquery',
        'mage/mage'
    ], function($){
        var $adjustmentForm = $('#swarming_credits_adjustment');

        $adjustmentForm.mage('form').mage('validation');
        $adjustmentForm.on('afterValidate.beforeSubmit', function () {
            $adjustmentForm.trigger('processStart');
        });
    });
</script>
